'use client'
import { useState } from 'react'
const B=[3200,46800,47200,45600,33800,12600],MX=Math.max(...[3200,46800,47200,45600,33800,12600])
export default function AccountPage(){
const[p,setP]=useState('Last 30 days')
return(<div style={{flex:1,overflowY:'auto',fontFamily:'system-ui',background:'#fff'}}><div style={{maxWidth:900,margin:'0 auto',padding:'28px 32px'}}>
<h1 style={{fontSize:22,fontWeight:700,margin:'0 0 24px'}}>Account</h1>
<div style={{display:'flex',alignItems:'center',justifyContent:'space-between',marginBottom:28,paddingBottom:24,borderBottom:'1px solid #F0F0F0'}}>
<div style={{display:'flex',alignItems:'center',gap:14}}><div style={{width:48,height:48,borderRadius:10,background:'#111',display:'flex',alignItems:'center',justifyContent:'center',fontSize:18,fontWeight:700,color:'#fff'}}>P</div>
<div><div style={{fontSize:16,fontWeight:700}}>Personality Pop-Up</div><div style={{fontSize:13,color:'#888'}}>hello@personalitypopup.com</div></div></div>
<div style={{display:'flex',gap:8}}><button style={{padding:'8px 16px',border:'1px solid #E0E0E0',borderRadius:8,background:'#fff',cursor:'pointer',fontSize:13,fontWeight:500}}>Edit profile</button><button style={{padding:'8px 16px',border:'1px solid #E0E0E0',borderRadius:8,background:'#fff',cursor:'pointer',fontSize:13,color:'#888'}}>Log out</button></div></div>
<div style={{display:'flex',alignItems:'center',justifyContent:'space-between',marginBottom:16}}>
<h2 style={{fontSize:16,fontWeight:700,margin:0}}>Earnings</h2>
<div style={{display:'flex',gap:8}}><select value={p} onChange={e=>setP(e.target.value)} style={{padding:'6px 12px',border:'1px solid #E0E0E0',borderRadius:20,fontSize:13,background:'#fff',cursor:'pointer'}}>{['Last 30 days','Last 90 days','This year','All time'].map(o=><option key={o}>{o}</option>)}</select><button style={{padding:'7px 14px',border:'1px solid #E0E0E0',borderRadius:20,background:'#fff',cursor:'pointer',fontSize:13,fontWeight:500}}>Export all earnings</button></div></div>
<div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:12,marginBottom:24}}>{[{l:'Total earnings',v:'$209,478.05',s:'Includes sales tax',h:false},{l:'Sales tax',v:'$0',s:'Total collected',h:false},{l:'Outstanding invoices',v:'$74,611',s:'Future earnings, due and past due',h:true}].map(x=>(<div key={x.l} style={{padding:'18px 20px',border:x.h?'2px solid #F5E6D3':'1px solid #F0F0F0',borderRadius:10,background:x.h?'#FFFAF5':'#fff'}}><div style={{fontSize:12,color:'#888',marginBottom:4}}>{x.l}</div><div style={{fontSize:26,fontWeight:700}}>{x.v}</div><div style={{fontSize:12,color:'#888',marginTop:2}}>{x.s}</div></div>))}</div>
<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginBottom:28}}>
<div style={{border:'1px solid #F0F0F0',borderRadius:10,padding:'16px 20px'}}><div style={{fontSize:13,fontWeight:600,marginBottom:12}}>Earnings by session type</div><div style={{height:6,borderRadius:3,background:'#C4A882',marginBottom:12}}/><div style={{display:'flex',justifyContent:'space-between'}}><div style={{display:'flex',alignItems:'center',gap:8}}><div style={{width:10,height:10,borderRadius:'50%',background:'#C4A882'}}/><span style={{fontSize:13}}>Mini Sessions 25</span></div><span style={{fontSize:13,fontWeight:600}}>$209,478.05</span></div></div>
<div style={{border:'1px solid #F0F0F0',borderRadius:10,padding:'16px 20px'}}><div style={{fontSize:13,fontWeight:600,marginBottom:12}}>Weekly earnings</div><div style={{display:'flex',alignItems:'flex-end',gap:6,height:100}}>{B.map((b,i)=>(<div key={i} style={{flex:1,display:'flex',flexDirection:'column',alignItems:'center',gap:3}}><div style={{width:'100%',background:'#C4A882',borderRadius:'3px 3px 0 0',height:Math.round((b/MX)*90)+'px'}}/><div style={{fontSize:9,color:'#888'}}>W{i+1}</div></div>))}</div></div></div>
<div style={{border:'1px solid #F0F0F0',borderRadius:10,padding:'20px 24px'}}><h2 style={{fontSize:16,fontWeight:700,margin:'0 0 16px'}}>Subscription</h2><div style={{display:'flex',alignItems:'center',justifyContent:'space-between'}}><div><div style={{display:'flex',alignItems:'center',gap:10,marginBottom:4}}><span style={{fontSize:15,fontWeight:600}}>Session Pro</span><span style={{fontSize:11,background:'#E8F5E9',color:'#2E7D32',padding:'2px 8px',borderRadius:10}}>Active</span></div><div style={{fontSize:13,color:'#888'}}>Billing monthly $19/Month USD</div></div><div style={{display:'flex',gap:8}}>{['Manage subscription','Update payment method','View invoices'].map(l=>(<button key={l} style={{padding:'8px 12px',border:'1px solid #E0E0E0',borderRadius:8,background:'#fff',cursor:'pointer',fontSize:12}}>{l}</button>))}</div></div></div>
</div></div>)}